region_name: western_canada_us
region_run_settings:
  altimetry:
    exclude_annual_datasets:
    - null
    - null
    exclude_trend_datasets:
    - null
  demdiff_and_glaciological:
    exclude_annual_datasets:
    - UZH_GlaciolSineWave
    - WGMS-mean_ba
    - Menounos_WNA_glac
    exclude_trend_datasets:
    - null
    include_combined_annual_datasets:
    - DUS-combined
    - Huss
    include_combined_trend_datasets:
    - DUS-combined
    - Huss
  gravimetry:
    exclude_annual_datasets:
    - null
    - null
    - null
    - null
    exclude_trend_datasets:
    - null
    - null
    - null
    - null
seasonal_correction_dataset:
  data_group: glaciological
  user_group: UZH_GlaciolSineWave
year_type: glaciological
